### ISSUE TITLE
Compute some sample parameters for CKKS

### ISSUE THREAD

**Issue by shaih** [helibproject/HElib#18]
To get closer to a quick-start guide is to build some tables for CKKS parameters. For now, this would just be provided as documentation... we don't necessarily need code that does anything.

For security=128, and for m=2^k for various k (up to, say, 17), we want to know the largest value of L (i.e. bits in ctxtPrimes) that can be chosen that gives this security level.  For a given L, you have to actually run a test program to determine the actual number of bits in ctxt and special primes. We could print out different L's for a few choices of c (which is the number of columns in the key-switching matrices).

There may be weird rounding effects that can happen, so maybe we'll write a program that build a context and runs buildModChain in a loop on L, and for each L prints out the total size S of ctxt+special. Then just eyeball it to see where S exceeds the # of bits allowed at a given security level, and make sure that for smaller L's, S is actually smaller.

We could also could do all of the above for security=80.

Once we have this program above, maybe we can also turn it into a tool that people can use to get the params for a required depth.

**Comment by faberga** [comment]
Resolved by PR #22
