### ISSUE TITLE
Ptxt and PGFFT tests failing after -march=native

### ISSUE THREAD

**Issue by esteffin** [helibproject/HElib#21]
After adding `-march=native` to compilation flags, two tests are failing due to floating-point rounding.
 - `Ptxt` test `TestPtxtCKKS.incrementalProductWorksCorrectly`
 - `Ptxt` test `TestPtxtCKKS.timesEqualsOtherPlaintextWorks`
 - `Ptxt` test `TestPtxtCKKS.multiplyByMultipliesCorrectly`
 - `Ptxt` test `TestPtxtCKKS.cubeCubesCorrectly`
 - `Ptxt` test `TestPtxtCKKS.timesOperatorWithOtherPtxtWorks`
 - `PGFFT` test when using clang on linux

This is because of the way floating-point comparison is done in the tests (by using `EXPECT_EQ` instead of `EXPECT_NEAR`).

Note none of this tests involves encryption, so they are not CKKS-related error.

@faberga knows how and will fix this.

**Comment by faberga** [comment]
Fixes:

- [ ] Ptxt test TestPtxtCKKS.incrementalProductWorksCorrectly
- [ ] Ptxt test TestPtxtCKKS.timesEqualsOtherPlaintextWorks
- [ ] Ptxt test TestPtxtCKKS.multiplyByMultipliesCorrectly
- [ ] Ptxt test TestPtxtCKKS.cubeCubesCorrectly
- [ ] Ptxt test TestPtxtCKKS.timesOperatorWithOtherPtxtWorks
- [ ] PGFFT test when using clang on linux
