### ISSUE TITLE
Add support for Travis-CI test system

### ISSUE THREAD

**Issue by esteffin** [helibproject/HElib#7]
Add support for the Travis-CI test system.

It should be capable to:
- [x] build LibBuild configuration
- [x] test the LibBuild configurations
- [x] build PackageBuild configuration
- [x] test the PackageBuild configurations
- [x] test the example programs
- [x] test utilities

Testing OS, should include:
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] MacOs (Mojave or Catalina)

**Comment by faberga** [comment]
Resolved by PR #24
